# Form implementation generated from reading ui file '/home/micha/prog/python/nexus_mod_manager/src/app/ui/frm_add_api_key.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


