# Form implementation generated from reading ui file '/home/micha/prog/python/nexus_mod_manager/app/uic/dlgAddMod.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAddMod(object):
    def setupUi(self, dlgAddMod):
        dlgAddMod.setObjectName("dlgAddMod")
        dlgAddMod.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgAddMod)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(dlgAddMod)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 381, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutAddMod = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutAddMod.setContentsMargins(0, 0, 0, 0)
        self.formLayoutAddMod.setObjectName("formLayoutAddMod")
        self.labelGame = QtWidgets.QLabel(dlgAddMod)
        self.labelGame.setGeometry(QtCore.QRect(10, 10, 381, 16))
        self.labelGame.setObjectName("labelGame")

        self.retranslateUi(dlgAddMod)
        self.buttonBox.accepted.connect(dlgAddMod.accept)
        self.buttonBox.rejected.connect(dlgAddMod.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgAddMod)

    def retranslateUi(self, dlgAddMod):
        _translate = QtCore.QCoreApplication.translate
        dlgAddMod.setWindowTitle(_translate("dlgAddMod", "Add a mod to a game"))
        self.labelGame.setText(_translate("dlgAddMod", "Add mod to game %s"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgAddMod = QtWidgets.QDialog()
    ui = Ui_dlgAddMod()
    ui.setupUi(dlgAddMod)
    dlgAddMod.show()
    sys.exit(app.exec())
